### ISSUE TITLE
model prediction not according to trained sequences. 

### ISSUE THREAD

**Issue by floriancartuta** [bluesheeptoken/CPT#82]
After training the model on a set of sequences, it almost always predict same item irrespective on the input sequence. For example:
`model.retrieve_sequence(10) output is ['10502162', '10501010', '10500860']` 

Then when I predict using the first two items from the learned sequence: `model.predict(['10502162', '10501010'])`, the output is
['11012517', '11012517']. 
I was expecting to have the third item in the learned sequence as prediction. Secondly, the item '11012517' is almost always predicted, no matter the input sequence.

Can you please check and clarify this behavior?

**Comment by bluesheeptoken** [comment]
Hello Florian
Thanks for opening a PR, sorry for the delay, I had not seen it.

> model.predict(['10502162', '10501010'])

`CPT` requires a list of sequences to predict. What is the output if you try `model.predict([['10502162', '10501010']])` ? I think it would be `['10500860']`

I do agree the methods exposed are very confusing, I will probably change them in the next major release.

> Secondly, the item '11012517' is almost always predicted, no matter the input sequence.

As a wild guess, I would say '11012517' is your first item in your training set. This happens when `CPT` cannot find any item to predict, it predicts the first item. I should add a log to warn about this behaviour.

Can you confirm `model.predict([['10502162', '10501010']])` is what you are looking for ?

**Comment by floriancartuta** [comment]
Hello Louis,

Concerning "_What is the output if you try model.predict([['10502162', '10501010']]) ? I think it would be ['10500860']"_, I already answered in the PR: is ['11012517', '11012517'].

**Comment by bluesheeptoken** [comment]
Hello Florian,

As I can see in the comment of the issue, you tried `model.predict(['10502162', '10501010'])`.

I would like to try `model.predict([['10502162', '10501010']])` (note the double squared brackets)

Can you confirm me the output ? (I expect to see a list with only one element)

---

Sorry for this confusing API, I will try to do something about it in the next major version of CPT :)

**Comment by floriancartuta** [comment]
Hello Louis,

Didn't noticed the double squared bracket. Indeed the output is: ['10500860']

**Comment by bluesheeptoken** [comment]
Does this answer your problem ? Can I close the issue ?

Do not hesitate to star the project if you enjoy CPT during your tests

**Comment by floriancartuta** [comment]
Yes. Thank you.
